### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by aferraz** [Filipowicz251/mijia-1080P-hacks#10]
Hi @willthrom,
 is this the correct camera https://www.gearbest.com/ip-cameras/pp_615275.html

Thanks
 Alessandro

**Comment by kollaesch** [comment]
Yes, it is ...

However, it might be that the cam the you'll get send will already have a newer firmware.
Please read the comments of the release how to downgrade.

**Comment by aferraz** [comment]
Thanks @willthrom 
 I already downgrade to the firmware in release 3 and then I put all files in the SD Card but after reboot I can't access SFTP or RTSP.

What is wrong ?

**Comment by willthrom** [comment]
Can you check/upload the logs files?

When the tools are working the LEDs on the camera flashed randomly, blue and red at the same time...

**Comment by aferraz** [comment]
The red is blue, my current firmware version is 3.3.6_099

**Comment by willthrom** [comment]
The tools creates some logs files in the SDCard

**Comment by aferraz** [comment]
Running Customm Script v1.5

Configuration:
  CLOUD_DISABLED=0
  CLOUD_STREAMING_DISABLED=0
  RTSP_ENABLED=0
  RTSP_MODE=s
  SSH_ROOT_PASS=qwerty123456
os-version
NAME=Buildroot
VERSION=2016.02-git-00292-gca900c9-dirty
ID=buildroot
VERSION_ID=2016.02-git
PRETTY_NAME="Buildroot 2016.02-git"
XIAOMI_VERSION=3.3.6_0099
XIAOMI_BUILDNO=312  
 Staring SSH Server
 Getting root access 
Changing password for root
New password: 
Retype password: 
Password for root changed by root

...Starting dropbear
[203] Jan 01 08:00:09 Running in background

Changing Language to English
Adding Protecction to Change of Keys..post
cp: can't stat '/tmp/sd/tools/pre-ota.sh': No such file or directory
Added second phase

**Comment by willthrom** [comment]
ok, good, there is a bug in the scripts.. I will take a look and upload a new release

**Comment by willthrom** [comment]
actually, that shouldn´t the camera.... ssh is there..

Can you test SSH?

**Comment by aferraz** [comment]
No, "Connection refused"

**Comment by willthrom** [comment]
Remove the Log files from the SDCARD and restart the camera.....

Then check if the Leds in the Camera change from Red to Blinking Blue and Red at the same time for 5s.

Then try to connect to the camera. How are you discovering the IP of the camera? Checking in the router?


After a couple of tries if still doesn´t work, power off the camera and upload the logs again.

**Comment by aferraz** [comment]
After boot the led is Red, then blink 3 times blue and then it remains blue,
I discover the IP from the dhcp logs

**Comment by willthrom** [comment]
UPLOAD a new set of logfiles after previously removing them from the sdcard

**Comment by kollaesch** [comment]
Did you start the cam for the first time?
I assume it's just stuck in the initial state of binding to the Wifi?

I also had issues getting release 0.4 running. You start with a clean SD-card.
(just to rule that out)

**Comment by willthrom** [comment]
Btw, RTSP_ENABLED=0 has to be 1 in midgard.ini file.

But first upload the new logs. It is very weird add the initial scripts are working. You can see the SSH server is up in the logs...

**Comment by aferraz** [comment]
I have rebooted the cam more times but no others logs have been created after deleting the old one.
I can reach the camera with the app and I cant ping it.

**Comment by kollaesch** [comment]
Just to be sure: 
> I **can** reach the camera with the app 
> and I **can't** ping it.

correct?

Is bluetooth enabled on your phone (where the app is running)?
The connection then might be via bluetooth.

**Comment by willthrom** [comment]
mmm.... That is weird. Is the camara still on 109 version?.

Try this. Copy 0.4 release into the SDCard and the tf_recovery.img. Restard the camera, it will  downgrade. After it reboots, upgrade straight away to 139.


Another thing you can do it is just to copy 0.5 release again to SDCARD.  Check if the logs are created now

**Comment by aferraz** [comment]
@willthrom I change the password for root in the config file and now it work
I don't know  if it is a case but now work ssh and streaming

**Comment by willthrom** [comment]
???? That is very weird

**Comment by aferraz** [comment]
I agree but now it works
