### ISSUE TITLE
Cant Downgrade

### ISSUE THREAD

**Issue by Nanoc0re** [Filipowicz251/mijia-1080P-hacks#11]
For some reason i cant downgrade i have copy the tf_recovery.img.bak to sdcard and rename it to tf_recovery.img  after powering the camera up it just still doing a normal boot and nothing have change

**Comment by willthrom** [comment]
Download the file again, just in case. It has to be in root of the SDCard.

You can check if the SDCard is fat32. From the MiHome you can validate the status of the SDCard as well.

**Comment by Nanoc0re** [comment]
The first time i try with ex-fat format after change it to fat32 and nothing, i see a small difference with fat blink for 1 min just blue but again nothing change, the status of SDcard is good and the file is in root

**Comment by willthrom** [comment]
Are you sure you have a Mijia 1080? That downgrade method has been used but a lot of people already...

It is actually coming from: http://en.miui.com/thread-525318-1-1.html

**Comment by lokster** [comment]
Try formatting it from the MiHome app. I had similar problem. It worked when I formatted it from there.

**Comment by Nanoc0re** [comment]
Thanks for the answers i will try again today

**Comment by snoerenberg** [comment]
I recognized that 64GB SDCards are only supported after the boot.
I could not get the hack to run on >32GB.

@Nanoc0re which size of SD Card you tried?

**Comment by willthrom** [comment]
Basically because normally fat32 has a 32GB limit.....    with 4GB file size limit.

It is true some system can accept bigger limits but u-boot could just not accept them...

**Comment by willthrom** [comment]
Closing this issue as it is not related to the "tools"
