### ISSUE TITLE
Questio: do you thin it will be possible to compile & run Motion on this camera?

### ISSUE THREAD

**Issue by lokster** [Filipowicz251/mijia-1080P-hacks#13]
I'm talking about this app: http://www.lavrsen.dk/foswiki/bin/view/Motion/WebHome
If I can get this running on the camera, I don't need anything else :)

**Comment by willthrom** [comment]
Why would you need another tool analyzing the image?  The camera has already HARDWARE for that.

And  just run it is not actually the real problem, but how you are planning to provide the image from the camera to this tool....

It is quite easy using one of the SDK example for motion detection to create a tool to perform an action when motion is detected. Actually the hardware allows you to configure different region in the camera with different priorities and qualities, even disabling some areas...
