### ISSUE TITLE
RSTP over 0.4

### ISSUE THREAD

**Issue by niighthawk** [Filipowicz251/mijia-1080P-hacks#14]
Is it only me or RSTP's image over 0,4 have some glitch ?

**Comment by niighthawk** [comment]
every moving car, or people look like that over RSTP ... but my other cams are okay only the mijia 1080p .... 

https://youtu.be/M8jPchgIpRE

**Comment by willthrom** [comment]
The RTSPserver in the Mijia is test implementation coming from the ChipSet manufacturer.
Not very reliable. There is some work in a new RTSPserver using other libraries (like the one in fang camera), but there istn´t too many developers working on that....

Stay tune.. it might happen,

**Comment by m1yuan** [comment]
When Mijia streaming and RTSP streaming are both enabled, the SoC may be overloaded. Cloud you try to disable Mijia streaming and try again ?

**Comment by niighthawk** [comment]
Cloud is already Off inside the Valhalla.sh file... no ? 

## Config
##################################################################################			
CLOUD_DISABLED=$(awk -F "=" '/CLOUD_DISABLED/ {print $2}' $sd_mountdir/midgard.ini)
if [ -z "$CLOUD_DISABLED" ];then
 CLOUD_DISABLED=0
fi

CLOUD_STREAMING_DISABLED=$(awk -F "=" '/CLOUD_STREAMING_DISABLED/ {print $2}' $sd_mountdir/midgard.ini)
if [ -z "$CLOUD_STREAMING_DISABLED" ];then
 CLOUD_STREAMING_DISABLED=0
fi

RTSP_ENABLED=$(awk -F "=" '/RTSP_ENABLED/ {print $2}' $sd_mountdir/midgard.ini)
if [ -z "$RTSP_ENABLED" ];then
 RTSP_ENABLED=1
fi

RTSP_MODE=$(awk -F "=" '/RTSP_MODE/ {print $2}' $sd_mountdir/midgard.ini)
if [ -z "$RTSP_MODE" ];then
 RTSP_MODE=m
elif [ "$RTSP_MODE" != "m" ] && "$RTSP_MODE" != "j" ] && "$RTSP_MODE" != "s" ];then
 RTSP_MODE=m
fi

**Comment by willthrom** [comment]
CLOUD_STREAMING_DISABLED=0
CLOUD_DISABLED=0

1 to disabled......  

CLOUD_DISABLED is to avoid any communication with Xiaomi.
CLOUD_STREAMING_DISABLED is to start the Xiaomi Streamer...

**Comment by niighthawk** [comment]
only in the valhalla file or in midgard.ini too ?

**Comment by willthrom** [comment]
midgard.ini.... valhalla.sh shouldn´t be touched

**Comment by niighthawk** [comment]
Update on my problem. 

everything is disabled like you said, I also tried the release 0.5 with cloud OFF and the glitch is still present.

**Comment by willthrom** [comment]
Yep.. the current RTSP is a very light version... it shouldn´t glitch anyway but I would try when I have time with a new library

**Comment by niighthawk** [comment]
ok thk  👍
