### ISSUE TITLE
Mijia 360?

### ISSUE THREAD

**Issue by pronsta** [Filipowicz251/mijia-1080P-hacks#17]
Hi,

Does this hack works with the [Xiaomi Mijia 360](https://xiaomi-mi.com/ip-cameras/xiaomi-mijia-360-home-camera-white/)?

Thanks

**Comment by willthrom** [comment]
Nope. Mijia 360 is from a different manufacturer.
Maybe the CPU is the same and with some little work the "Tools" could work.
