### ISSUE TITLE
RTSP with MiHome

### ISSUE THREAD

**Issue by izoniz** [Filipowicz251/mijia-1080P-hacks#19]
Hi! I had installed patch. When I put in config CLOUD_DISABLED=0, CLOUD_STREAMING_DISABLED=0 and RTSP_ENABLED=1  I can't connect with RTSP. 
Can streaming work from MiHome and RTSP simultaneously?

**Comment by willthrom** [comment]
in the current version there is an issue when disabling the CLOUD.. basically it doesn´t really do anything...
A new release will be available soon.

And no. you cannot stream both at the same time, the driver of the camera doesn´t work every well doing that.
