### ISSUE TITLE
Restoring U-boot (+ Firmware)

### ISSUE THREAD

**Issue by willthrom** [Filipowicz251/mijia-1080P-hacks#2]
This is a work in progress.....  Gathering information

Camera Memory chipset (SPI NOR Flash): GD25Q128c (data-sheet on link)
http://www.gigadevice.com/product/detail/5/260.html?locale=en_US

**Assuming direct connection to the chip: USB SPI Programmer?**
https://en.wikipedia.org/wiki/Bus_Pirate ???
http://www.ebay.co.uk/itm/NANO-BIOS-Programmer-for-PC-M-B-BIOS-repairing-/280388472031 (lists this memory chip, version B)
http://www.ebay.co.uk/itm/CH341A-24-25-Series-EEPROM-Flash-BIOS-USB-Programmer-SOIC8-Clip-On-Board-UK-/162557028178?epid=1390692406&hash=item25d9276752:g:vG8AAOSwCQZZCi3S
**A possible memory replacement (for playing):**
-  http://www.ebay.co.uk/itm/W25Q-Winbond-Serial-Flash-Memory-Module-SPI-W25Q128B-BIOS-25Q64BVSIG-EEPROM-/181873964697?var=&hash=item2a58887699:m:myY3DImwzx8P87WoVXAYyiA
- http://www.ebay.co.uk/itm/1-St-Speicher-NOR-Flash-128Mbit-Quad-I-O-SPI-104MHz-2-7-3-6V-SOP8-/112464838446?hash=item1a2f6d3f2e:g:61sAAOSw7GRZL61E

JTAG not evaluated yet.... PIN? Board Support?

**Comment by willthrom** [comment]
Can anyone provide a better image of the memory chip in the camera board? GD25Q128c

**Comment by willthrom** [comment]
Closing because noone is working on it and it is not trivial to play with the flash memory.
Re-open if required (providing support to resolve it)

**Comment by andreq** [comment]
Did you try that "old" recovery image from Xiaomi forum? Could it just boot up (somehow?) and recover u-boot? You might be the only one with a bricked camera tho.

**Comment by snoerenberg** [comment]
@andreq the cam have not booted after NSBoot at all. No U-Boot boot was possible (afaik).

**Comment by willthrom** [comment]
@andreq  I created this issue for another person who mesh with the partition and broke something. Without too much experience the only solution I see is to flash the system directly to the chip. But it is up to that user to play with it.

**Comment by andreq** [comment]
@willthrom yeah, forgot if it was you or @snoerenberg who had a bricked camera.

**Comment by willthrom** [comment]
none of us actually, was someone else

**Comment by andreq** [comment]
I'll go hide in a cave and try to wake up a bit more! Sorry for the spam

**Comment by willthrom** [comment]
no worries. this is a closed issue anyway.
