### ISSUE TITLE
Firmware downgrade

### ISSUE THREAD

**Issue by matsube11** [Filipowicz251/mijia-1080P-hacks#21]
> Users with Firmware .139 without the toolset already working, you will have to downgrade to a previous version

How do you proceed to downgrade firmware on this camera ? I couldn't find any relevant info to do this

**Comment by powerwade** [comment]
Download https://github.com/Filipowicz251/mijia-1080P-hacks/releases/download/0.3/release0.3_338.zip and copy the tf_recovery.img.bak file to the SD card and rename it to tf_recovery.img. Put the SD back to the camera and boot it. The camera will be downgraded.

**Comment by willthrom** [comment]
Closed as the instructions by @powerwade  are the correct ones. (they are in the release as well but I will make it clear)

**Comment by matsube11** [comment]
Worked well thanks, untill I allowed firmware update.
New firmware 3.3.10_0146 broke it, so downgrading again

**Comment by willthrom** [comment]
try to ugprade with RTSP off leaving Xioami Cloud and Streaming ON. And OTA on........

**Comment by matsube11** [comment]
Again, that did the trick, great :)
And many thanks for your work
