### ISSUE TITLE
Tutorial Needed. 

### ISSUE THREAD

**Issue by tobbegutt** [Filipowicz251/mijia-1080P-hacks#22]
This is annoying. There is obviosly are more complex thing to downgrade and make the rtsp work than just "remove .bak" and put 0.7  or whatever obn your camera. There's gotta be a better tutorial than that? Is it depended on wich server? Why is it so hard to think that not everyone have the full on technological skill to figure this out so im sure theres at least 10 people here that have this working, how about one of you dedicate 4 minutes and just write down the correct prosedyre? Im here to help myself, but im stuck so how can i help others? We need to KICK the information around. Also post the tutorial on gearbest etc wich I am willing to do, but i need to get further than vagely questions if i even have the mijia wich of course i have and or "did you enable cloud?" I mean SHOULD I enable cloud? What does it do? Why do i need to diable rtsp? How do i upgrade after having the red/orange flash wich shows the tools are working? And why after that i canot acces my camera in mihome? Is it because im on US server? IS it because its on 5GHZ wifi? is it because my sdcard are to small? Do i need to downgrade, then install tools, then take out sdcard reset and repair on us server? then upgrade and so put back in the sdcard? I mean theres gotta be ONE person here that knows all these questions?

So far im at least downgraded but after sdcard with tools i cannot access the camera in Mi home.

**Comment by willthrom** [comment]
The instruction are quite clear:
Use the latest version, default midgard.ini configuration.
Downgrade with the tools in the SDCARD.
Upgrade.

**Comment by tobbegutt** [comment]
nope

**Comment by tobbegutt** [comment]
just did that.
Fat32 sd card.
put in 0.7 and the recovery.
took out power, booted by holding reset. Went to pairing mode.
Paired and still on latest firmware and no rtsp.

So- since this is your tutorial. What did i do wrong?
Remember not all are having english at first language and have the skill to dissasemble a camera like you have. Take it down many notch.

**Comment by tobbegutt** [comment]
@willthrom

**Comment by willthrom** [comment]
No one has said anything about going to "reset" mode to pair the camera again.

In any case, I feel like you are "demanding" too much here, and this is a open source project where no one is getting anything except putting some of their free time in working on this.

**Comment by tobbegutt** [comment]
Im sorry if my english skills are not good enough to ask in a more polite way.
Im here to get past this issue so i can contribute setting up this camera for surveillance using Ispy connect and to make sure the thousands of other people wich also bought this camera can get the full monty.

Look, i tried again without reset., No luck.

I tried again now, taking out the sdcard making sure i get the rename correct. Rebooted. Nothing.
Is it because im on US server?
Any help would be appreciated.
And im sorry but "noone" have taken their time to make sure to wwrite a n00bfriendly tutorial either.
I understand its all in others free will and time, im here to contribute myself but i cannot because i dont have a foolproof tutorial on the first step.  @willthrom

**Comment by tobbegutt** [comment]
As i understand if this work correctly i can acces the camera both from Mihome and from Rtsp is that correct? Because that is my issue. I can just access rtsp and only rtsp on 099 firmware

**Comment by willthrom** [comment]
Steps:

1. Configure the Wifi following the Xiaomi steps.
2. Check the camera is reachable and the video streaming is available using the XIaomi MiHome tool.
3. Power off the camera
4. Copy from the release.0.3 the file tf_recovery.img.bak to a Fat32 (max 64Gb) clean sdcard
5. Rename tf_recovery.img.bak to tf_recovery.img in the sdcard
6. Reboot the camera
7. Yelow leds will turn on
8. Wait 5min
9. Check with MiHome the firmware is 0099 (normally in the upgrade option)
10. Power off camera
11. Then copy the 0.7.1 release in the SDCARD (after decompress).
12. Edit midgard.ini and set all the options to ´0´ (Disabled)
13. Insert the card in the camera and reboot.
14. Check if the LEDS in the camera blink yellow and blue.
15. Power off the camera
16. Check if a log folder has been created and a file with the extension log is in the root of the sdcard.
17. Move them from the SDCARD 
18. Insert the SDCARD in the camera.
19. Power on the SDCARD
20. Using MiHome upgrade to the latest version.
21. Power off SDCARD
22. Power on SDCARD 
23. Check if the LEDS in the camera blink yellow and blue (5 seconds)
24. Power off the camera
25. Check if a log folder has been created and a file with the extension log is in the root of the sdcard.
26. Edit midgard.ini configuration file to enable the different services, like RTSP.
27. Insert the SDCARD in the camera.
28. Power on the SDCARD
29. Check if the LEDS in the camera blink yellow and blue.
30. Check if RTSP server works.

**Comment by tobbegutt** [comment]
Nope.

after downgrading, and doing all the steps i can only connect using rtsp.
I cannot connect using mihome.
Tried injecting default midgard but no difference.
Tried taking out sdcard and connect, but then it wouldnt turn on. orange steady light.
tried then after trying several servers with the tool working to open mihome but no luck.
I then tried to update after reset and inject the working sdcard, but after on/off on the camera it will not give orange/blue fflash and my camera again says im offline but i can still connect watching the stream in mihome but i cannot adjust anything.

I mean, Can i connect RTSP and MIhome at the same time?

If i cant i just realized i threw away 3 days for trying to get this to work.
The main issue is that my Sdcards in my 4 cameras are all on 2GB so after a day of motion detection even if i have connected to NAS the sdcard fills up and it stops recording so i need to format the card using network every day. This was a pain in the ass.  
And i also thought that if i got rtsp to work i could as a backup set up my laptop again with ISPY CONNECT as i had before on my foscams and having the files upload to Google drive in case i had a burglary.
But all this wich would have been foolproof dont work.
I can now either choose to format the card every day and having the ability to connect and see whats going on on my phone Mihome-
or
use RTSP and Ispy connect on my laptop and have no app on my phone wich allows me to connect and see whats going on. :(

Thats my main reason to be here. 
If the issue get worked out or you have a solution for having both at the same time ill be glad to help other out with ISPY and how to easily set up your own foolproof home surveillance system for free, 
I have used it for years but i cannot use it now because of i find the MIHOME to be essential to connect and see whos outside etc..

Anyway Thank you so much @willthrom  for taking your time with the tutorial and all this

**Comment by willthrom** [comment]
Both service will not work. The camera drops frames and has encoding when the RTSP server and the Xiaomi streamer are enabled at the same time.

You could use SMB of FTP to get the files from the camera and delete them after

**Comment by tobbegutt** [comment]
ahh.. fuck.. So i just wasted 3 days beliving both rtsp and mihome would work at the same time..
No wonder ive had a lot of problems. 
I had rtsp working on 099 firmware but not on the latest. Anyway.. forget that issue for now unless someone is working on having them both work togheter.

But since i cheaped out when i ordered my sdcards, if you dont mind lets talk about NAS for a second.
You see i have enabled the NAS i have and it records in folders with the Mac adress for the different cameras, and inside there again its folders for every hour of the day.
Its messy, is there some way i can configurate the nas settings in mihome, cus now its just so simple and basic.
And the issue for the sdcard to fill up are there a solution there? is there a way i can ONLY record to NAS and not to Sdcard when motion are detected?
Thank you @willthrom , i still are able to help out with ispy for those people that choose rtsp over mihome. :)

**Comment by willthrom** [comment]
RTSP and Mi will even work together because the issue is coming from the driver of the camera, unless some decide to play with it but I really doubt it.

I don´t use NAS so I don´t have take a look the Xiaomi NAS binaries. Someone might help you there, I just don´t have the time.
