### ISSUE TITLE
Tutorial for flashing Mijia 1080p in case of upgrade issues

### ISSUE THREAD

**Issue by ferdydek** [Filipowicz251/mijia-1080P-hacks#23]
I had issues upgrading and keeping the tool on the camera, so after many trial-errors this is the method that worked for me.

**Preparations:**
Download https://github.com/Filipowicz251/mijia-1080P-hacks/releases/download/0.3/release0.3_338.zip and copy tf_recovery.img.bak  to empty FAT32 SD card. Rename the file to `tf_recovery.img`.
You will be flashing `3.3.6_0099` FW which really does work properly only with **china-mainland** server, I strongly suggest switching to this server for the time being. 
Flash the firmware and use reset button to go through MiHome setup process. 

  _3.3.6_0099 and Secure WiFi issue_:
  If during setup of the camera (after you scanned the QR code) there is a timeout (usually at around 80%-89% of progress), you are being victim of a bug in Mi's fw. Its pretty easy to solve:

- create WiFi access point on your phone or router without any authentication
- connect your phone to that network and reset-setup camera again using this network 
- go through the firmware update process still connected to this open WiFi.
- reset the device to use your normal WiFi wile on newer firmware. 
- repeat the flash `tf_recovery.img` of 0099 firmware again. 	

...this way your WiFi settings are saved in `nvram` and will stay there until next time you use the reset button, these setting prevail through FW upgrades and hack. 
	
**Installing the tool:**
Download zip from https://github.com/Filipowicz251/mijia-1080P-hacks/releases/latest/ and extract all to SD card. 
On SD card edit the `midgard.ini` file and set `0` for these:
```
	CLOUD_DISABLED=0
	CLOUD_STREAMING_DISABLED=0
	RTSP_ENABLED=0
	DISABLED_OTA=0
```
On the  SD card make a copy of the `ft` folder, lets call it `ft2`.

Power on the camera and be patient, this is not i7.  You should see orange light, first stable, later slowly flashing. At some point you should hear the _click_ on night-vision mode when the device reboots. After that pay attention to quick flashes of blue-orange light (5 times). This means the `tool/hack` gets installed.

Try to connect via SSH, again be patient, if it doesnt work give it a minute. Once you get SSH access means the tool worked and now we just need to update it.

**Keeping the hack:**
On ssh list the content of the SD card to make sure we can safely reboot the camera .
From `ls -la /tmp/sd/` you should see the `ft` folder still there. if the folder is gone lets restore it from the copy we made earlier 
```
cp -R /tmp/sd/ft2 /tmp/sd/ft
```
Wait one more minute and reboot the camera.
After reboot (be patient) try the SSH first. If you have access then everything is good.

**Upgrading:**
MiHome app should see the camera and should show notification that there is a new FW update.
Dont update yet, we want to make sure ssh access/tool is still accesible after reboot. Reboot and connect ssh again.

I went through this process few times and each time the Mi behaves a bit different, but be patient.
When you start the upgrade process via MiHome app the camera will start flashing orange light. There will be prograss % on the MiHome app but even if it fails or times out on the app, let the camera finish its process. If the light is blinking do not touch it. Let it be.
This will take forever but will eventually complete the flash and reboot (you will hear the nightvision click again).

Now you can SSH to the camera again and change the settings in `midgard.ini` to fit your needs.

Good luck!

**Comment by willthrom** [comment]
@ferdydek  what do you think if we merge what I wrote in the ticket "https://github.com/Filipowicz251/mijia-1080P-hacks/issues/22#issuecomment-341978523", check the list of steps and the good work you did here and move it to the Wiki. https://github.com/Filipowicz251/mijia-1080P-hacks/wiki

Feel free to edit it at will, I just think it is better than having an issue ticket opne difficult to reference to.

**Comment by Eth3rkni6ht** [comment]
Hi guys!
Thanks so much for this valuable info. My camera got stuck on orange light after first firmware update via the Mi app just 5 minutes after unboxing it, and I was quite frustrated. Following the process I could get it to work again :+1: 
Now I'll try the hacks here

**Comment by gugadandrea** [comment]
How do I flash this firmware? Same problem here, right after I opened the box, I installed the camera, it updated and got stuck in the orange light. Should I copy just the image or all the content of the ZIP file?
