### ISSUE TITLE
Raise motion detected clip length

### ISSUE THREAD

**Issue by jzeferino** [Filipowicz251/mijia-1080P-hacks#24]
There is any way/hack to raise the length of the recorded motion detection clips?

**Comment by tobbegutt** [comment]
should be made like, record all the time while it got motion, but to be able to short the clips to maybe 5 minutes length? i dunno. great idea.



Sent from my MI MAX 2
On "J. Zeferino" <notifications@github.com>, 6. nov. 2017 23.15 wrote:

There is any way/hack to raise the length of the recorded motion detection clips?

**Comment by jzeferino** [comment]
Yes, would be nice to customize the time to record after motion is detected. But 5 minutes could be the default.

@tobbegutt do you know if there is any way to get more than 12/10 secs of recorded data using the original firmware and application?

**Comment by tobbegutt** [comment]
Yes. I have a Nas and it makes 1 minute files and upload them to my hdd. But, the stupid thing is that its 1 minute without recording before next clip due to motion sensor activation. The app should be reworked and made better.

**Comment by willthrom** [comment]
I haven´t seem any config value for the duration of the motion clips.

no under any .cfg file or nvram show.

you could try to play with "/gm/config/gmlib.cfg"

**Comment by tobbegutt** [comment]
Im not skilled enough to understand what i should do with this config.
