### ISSUE TITLE
Is it possible to make this camera work with YI Home app?

### ISSUE THREAD

**Issue by designlook** [Filipowicz251/mijia-1080P-hacks#26]
The app is so much better than MI Home.

**Comment by AshPowell** [comment]
I wasn't sure so when I first got my cam a while back, I tried to set it up with it and now can't get it to pair or anything with the proper app, even after restoring firmware.... So I doubt it

**Comment by willthrom** [comment]
The camera connects to Xiaomi Server, whatever server you configure when pairing with the mobile.
After that all the communication is done from the camera to the Xiaomi Server and from there to whatever other application is able to connect to Xiaomi Server.

Can you provide a link for the YI Home App? I really though there was only one MiHome for all Xiaomi Smart Devices, however the interface changes depending on the server you are connected to.
