### ISSUE TITLE
first attempt...

### ISSUE THREAD

**Issue by anxdroid** [Filipowicz251/mijia-1080P-hacks#27]
hello guys and many thanks for your work. I just tried to flash your hack (with the downgrade) and the situation of my cam is as follow: 

- ssh and rtsp are working

- the camera is not recognized by the mi platform (the android app tells me that is offline)

- performing a reset I can still hear the chinese voice 

For now it's enough for me,  but I want to achieve the best result, if possible :-)

I can access the camera via ssh but at login I have this three error/warning messages: 

[523] Nov 14 21:17:40 lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
[523] Nov 14 21:17:40 lastlog_openseek: /var/log/lastlog is not a file or directory!
[523] Nov 14 21:17:40 wtmp_write: problem writing /var/log/wtmp: No such file or directory

Rtsp is also working and with default settings (1080p) on local wlan I can see a smooth video with a delay of 4/5 secs. Is this normal/acceptable ?

I am wondering into the system to better understand how to configure it. Is there a logfile ? Can I modify the .ini configuration file directly from the camera ? What happens if I issue a "reboot" command ? 

If possible I would like to contribute to your work..

**Comment by debsahu** [comment]
I'm facing similar issues, check https://gitter.im/fang-hacks/Mijia-1080P The OP is quite active and a few are helping out.

**Comment by willthrom** [comment]
The /var/log/lastlog error is normal. It is because the / partition is read-only and by default login creates those files if they are not there.

4/5s seems a lot, usually is 1-2 sec.
Did you disable Xiaomi Streaming from the configuration file: midgard.ini?

Running RTSP server and Xiaomi Streaming Server will definetely product delays, image distorsion and frames drop.

Regardin editting, yes, I do that using WinSCP/Putty, and then run reboot. (it should work).

**Comment by anxdroid** [comment]
thanks for your reply. I didn't disable the Xiaomi server because I read that such function wasn't working properly. I'll give it a try.. Yesterday I tried a fresh install with rtsp ON, ssh ON and cloud streaming ON and it worked with both the hack and xiaomi services active. I ran an update to the latest version (3.3.10_0146) and, after that, the hack disappeared: no ssh and no rtsp (used android app fing to scan active ports on the camera's IP)

**Comment by willthrom** [comment]
As it is mentioned in the instructions. when upgrading, use the default configuration file, midgard.ini from the release, as sometimes the process doesn´t finish properly because the RTSP or any other service is still running.

(what might no be working is the Disabling OTA  option)

**Comment by 1980georgeg** [comment]
I've just ordered another mijia - I'm running at the moment an older one that had the earlier fw to begin with. Once I get this new one up and running with the downgrade, are there any real reasons to update the fw afterwards? I haven't touched my current one out of fear I'll bork it with new fw.
