### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by Killbrum** [Filipowicz251/mijia-1080P-hacks#28]
Hello

Thanks for releasing such hack. I have one small question. Is this hack ready for production usage? I need only two things.
- RTSP
- DHCP with reconnection ability 

Thanks!

**Comment by willthrom** [comment]
Production? Well we are still waiting for the QA department to finish the Integration Test. Then the release management team will follow the procedure signed by the architect and the delivery will be done by the Project Manager.....

RTSP works.... people hasn´t complained
The camera connects automatically to the WIFI, but there isn´t any DNS server or broadcast

**Comment by Killbrum** [comment]
Thanks for quick reply.

What about DHCP client? I have old xiaomi mi ants with DHCP support. At first look, I didn't find any configuration for static/dynamic IP address assignment. It seems WiFi SSID/PWD options also doesn't exist.

Could you point me where I can find these settings? 

Thanks

**Comment by willthrom** [comment]
Wifi option doesn´t exist because it is done when pairing the camera the first time you power up the camera or when resetting it with the button.

Using SSH the Wifi config can be changed manually, nvview  (or nv* something)
