### ISSUE TITLE
New recovery file?

### ISSUE THREAD

**Issue by powerwade** [Filipowicz251/mijia-1080P-hacks#30]
Hi, as we all know since the latest upgrade the whole hack is broken, so I am wondering if it possible to manually generate a new tf_recovery.img file somehow from the available upgrade files? Or is there a recent recovery file that is not 0.99? I recently received my second unit, but unluckily it has version .140 so I have no other choice but downgrade to 0.99.

**Comment by willthrom** [comment]
unfortunatelly the .img files are signed. Maybe there is a way but I haven´t found enough information about  it.
When I have time, I will prepare a new version of the tooling with an option to update the binary of the camera manually taken from the latest firmware.

Actually if you have time, you can take the latest fw. use binwalk to extract the binaries from the tffs2 partition and copy them to the /mnt/data folder (been in 099)

**Comment by powerwade** [comment]
Good idea, but it didn't work for me. I was able to get the files from the jffs2 partition and was able to overwrite everyhing on /mnt/data as suggested while I was on 099. But after reboot the camera says in Mi Home it's on version 139 (that one I tried, not the latest) and I lost ssh access. I might wait for your next version ;)

**Comment by powerwade** [comment]
Thanks for the idea, it worked. I am on .147 with ssh access. I copied evertything from the jffs extract, but ft and miio_ota dirs.
