### ISSUE TITLE
Remotely enable/disable motion detection

### ISSUE THREAD

**Issue by inggaro** [Filipowicz251/mijia-1080P-hacks#31]
Hi, I think it would be great to add a way to enable/disable motion detection, I want to link it to my alarm system and I just need a way to call a command (it would be great if supported by the internal web server).

Thanks!

**Comment by willthrom** [comment]
No one is working in the webserver so you could do it with running a ssh command.

nvram is the command with the configuration in the NAND.
Take a look to nvram show.

when you figure out the exact command, you can execute it outsite.
