### ISSUE TITLE
Latest update 0154 ssh not working

### ISSUE THREAD

**Issue by Sh1n1x** [Filipowicz251/mijia-1080P-hacks#32]
Here is my latest log file 

```Running Customm Script v1.7

Configuration:
  CLOUD_DISABLED=0
  CLOUD_STREAMING_DISABLED=0
  RTSP_ENABLED=0
  CONFIG_LINE=-b4098 -f20 -w1920 -h1080 -m1
  SSH_ROOT_PASS=qwerty123456
  DISABLED_OTA=0
  HTTP_ENABLED=0
  SAMBA_ENABLED=0
os-version
NAME=Buildroot
VERSION=2016.02-git-00292-gca900c9-dirty
ID=buildroot
VERSION_ID=2016.02-git
PRETTY_NAME="Buildroot 2016.02-git"
XIAOMI_VERSION=3.3.6_0099
XIAOMI_BUILDNO=312  
 Staring SSH Server
 Getting root access 
Changing password for root
New password: 
Retype password: 
Password for root changed by root

...Starting dropbear...

...Changing Language to English...
[205] Jan 01 08:00:09 Running in background
...Adding Protecction to Change of Keys...

Script Ends. Ok
[881] Jan 07 20:40:27 Child connection from 192.168.1.116:57844
[881] Jan 07 20:40:33 Bad password attempt for 'root' from 192.168.1.116:57844
[881] Jan 07 20:40:39 Password auth succeeded for 'root' from 192.168.1.116:57844
[205] Jan 07 12:46:06 Early exit: Terminated by signal
[881] Jan 07 12:46:06 Exit (root): Terminated by signal
[881] Jan 07 12:46:07 Exit (root): login_init_entry: Cannot find user "root"
Aiee, segfault! You should probably report this as a bug to the developer
```

**Comment by ferdydek** [comment]
Did you make a fresh install (flashed 0099, installed hack, updated to 0154) or you were previously on 0147 with working hack and updated to 0154 ?

**Comment by Sh1n1x** [comment]
I have made a fresh install with flash of 0099, install hack and update to 0154.

**Comment by vija24** [comment]
I was on 0147 hacked, and I have lost the hack (ssh Access) after update to 0154.
Any suggestions to recover the hack?

**Comment by ferdydek** [comment]
@willthrom what do you recon we should do?

**Comment by willthrom** [comment]
I haven´t had time to reproduce the issue but I would say to @vija24  to follow the procedure from the beginning, like you, @ferdydek , explain very accurate last time, meaning, reflashing to .99 and start over.

**Comment by ferdydek** [comment]
@Sh1n1x @vija24  can you pls comment back if you managed to get it sorted?

**Comment by sagilo** [comment]
I can confirm it here too.
Flashing the `tf_recovery.img` works and downgrades back to 0099.
SSH and RTSP works perfectly, so is the app stream being disabled.

However, as I upgrade to 0154 the hack can no longer be applied.

I've tried multiple times the whole procedure:
1. Flashing 0099
2. Installing the latest hack
3. Try accessing SSH / RTSP (works)
4. Upgrading to 0154
5. SSH/ RTSP not working
6. Re-installing hack
7. SSH/ RTSP not working
I've tried steps 6 & 7 several times, the hack never sticks.

I've also tried using version 7.1 of the hack with no success.

@Sh1n1x , @vija24 I'll be happy to get the steps to make this work over 0154, until then I'll have to use version 0099.

**Comment by Sh1n1x** [comment]
@sagilo for me nothing is working for the moment, this camera isn't hacked :/

**Comment by sagilo** [comment]
Thank you @Sh1n1x, I use the hack with version 0099 for now.. hopefully it will be fixed and I'll be able to upgrade my camera firmware

**Comment by ddtmax** [comment]
not works

**Comment by willthrom** [comment]
When somoone with an UART-Serial adaptor open its camera and read the logs I will be able to resolve this issue.

(I tried with mine but my soldering iron was in a very bad state and the result was the Tx Pin pulled out. Not I cannot read the logs any more)

**Comment by ddtmax** [comment]
solutions?

**Comment by sagilo** [comment]
Any suggestions ? this is still relevant for firmware 0158 with latest version (0.8.6)

**Comment by willthrom** [comment]
just try over downgrading to 99 with 0.8.6.

In any case, the steps are just.. downgrade to 99. with the latest release, test SSH there (or check if the camera led blinks orange/blue for 5s at boot time)
then upgrade to latest version
check SSH again
and then change MIDGARD.ini to enable RTSP

**Comment by sagilo** [comment]
Tried that more than 10 times, this doesn't work.
More users reproted the same over the chat.
I guess this isn't going to be fixed.
Thank you for your efforts

**Comment by willthrom** [comment]
what is not working?
Is ssh working when downgrading to 99?
Is ssh working when upgrading to 158?

Try with downgrading to 99 and upgrading to 158 with 0.8.5
