### ISSUE TITLE
the hack is deactivated when the camera is restarted

### ISSUE THREAD

**Issue by theDoc5655** [Filipowicz251/mijia-1080P-hacks#33]
I recently installed the latest version of the hack successfully but once the cam is restarted to be placed in its final location and its subsequent reboot, the change seems to have disappeared.

**Comment by andreq** [comment]
https://github.com/Filipowicz251/mijia-1080P-hacks/issues/29

It's been there for a while. Try to search a bit before adding a new issue :(

**Comment by ferdydek** [comment]
Also explained in:
https://github.com/Filipowicz251/mijia-1080P-hacks/wiki/Issues-installing-and-keeping-the-hack
