### ISSUE TITLE
QQ: Can you revert to stock firmware

### ISSUE THREAD

**Issue by rcmpayne** [Filipowicz251/mijia-1080P-hacks#37]
I want to test your firmware however, can one revert the mijia back to stock firmware? if so any steps

**Comment by BrendonKoz** [comment]
The project's Wiki has the answer to that (and explains how):
https://github.com/Filipowicz251/mijia-1080P-hacks/wiki/Recovery---Debrick

That should get you back to a 100% OEM-based install. As with anything that modifies firmware, it's not suggested to try this if you absolutely cannot be without the device as oddities can arise.
