### ISSUE TITLE
Artifacts while playing RTSP stream when objects are moving

### ISSUE THREAD

**Issue by sagilo** [Filipowicz251/mijia-1080P-hacks#38]
It happens pretty much constantly when objects are moving, impossible to ignore.
Maybe some kind of tuning is required for the RTSP lib?

**Comment by willthrom** [comment]
disable XIAOMI streamer in the midgard.ini file

Two streamers at the same time doesn´t work

**Comment by sagilo** [comment]
Thank you @willthrom 
Are you relating to the [this file](https://github.com/Filipowicz251/mijia-1080P-hacks/blob/master/sdcard/midgard.ini) ?
I don't see any option for Xiaomi Streamer there.

**Comment by willthrom** [comment]
????

## Streaming with Xioami Servers (0,1). Can be used with CLOUD_ENABLED to be able to manage the camera but not streaming outside your network.
CLOUD_STREAMING_DISABLED=0

**Comment by sagilo** [comment]
@willthrom It's already set to 0, but this feature is currently not working, see: https://github.com/Filipowicz251/mijia-1080P-hacks/issues/34

**Comment by willthrom** [comment]
CLOUD_STREAMING_DISABLED=**1**

**Comment by sagilo** [comment]
@willthrom I meant 1 as disabled, just got confused when writing the comment.
This doesn't help, artifacts still exist.
I really appreciate the work you put into this,  but IMHO I think you should let people a little bit more time to response :)

**Comment by willthrom** [comment]
CLOUD_ENABLED is a different option which is not 100% working.
CLOUD_STREAMING_DISABLED needs to be set to true to DISABLE the CLOUD Streaming.

RTSP doesn´t have more option for basic users and if doesn´t work it would be a connectivity issue.

For more advance user who knows what they are doing:

#### BITRATEMODE
#	 1  Constant Bitrate  
#        2  Variable Bitrate  
#        3  Enhanced Constant Bitrate  
#        4  Enhanced Variable Bitrate
CONFIG_LINE=-b4098 -f20 -w1920 -h1080 -m1

**Comment by sagilo** [comment]
Does the camera support 4096b?
What happens with the different bitratemodes, are they all supported?
