### ISSUE TITLE
Xiaomi Mijia 1080P Smart IP Camera as Network Camera?

### ISSUE THREAD

**Issue by mixpc** [Filipowicz251/mijia-1080P-hacks#40]
Hello,

This may be a newbie question but... can the Xiaomi Mijia 1080P Smart IP Camera be configured/firmware updated/hacked to work as Network Camera? The goal would be using it as a network camera (eg. http://192.168.1.5:80) that opensource software can have access to.

As of now with Xiaomi Mijia propietary latest firmware 3.3.10_0154 the camera can only be accessed via propietary Mi Home Android app.

Thank you in advance!

**Comment by willthrom** [comment]
Better to ask this question in the forum: https://gitter.im/fang-hacks/Mijia-1080P

regarding the Streaming.. that is the purpose of this tool projects.
