### ISSUE TITLE
Change the default RTSP port

### ISSUE THREAD

**Issue by tesnic** [Filipowicz251/mijia-1080P-hacks#41]
Hi guys!! Good hack, i use it to my synology surveillance station. I have two xiaomi cameras, but i cant configure both with de same 554 RTSP port. How can i change the default port???

Thanks!!

**Comment by willthrom** [comment]
Just use port forwarding in your router.... so from out site you can have port A pointing to cameraA IP_A Port:554 and Port B pointing to CameraB IP Port:554
