### ISSUE TITLE
Have troubles to install hack patch

### ISSUE THREAD

**Issue by cookins** [Filipowicz251/mijia-1080P-hacks#42]
i have issue with non working RTSP i think.
here what i doing - 
i copied files and dirs from dir that inside zip release. also i copied there img file.
![hack](https://user-images.githubusercontent.com/7893051/37939775-726cbcfe-316d-11e8-9691-a1c069fdde2e.png)
turned on device it was busy with yellow led blinking about minute. then it just shut off (at least led stop blinking). i waited for 1 minute more. then reconnected. its all like same except led was blinking with yellow and blue.
well after it i connected with phone like usual. all seems working -
(at least no Chinese talking, but no English either, and led flashing different), except what i need most - RTSP and HTTP stream!
im edit only midgard.ini file -
RTSP_ENABLED=1##
and
HTTP_ENABLED=1##
still nothing on camera ip 8080 port
and VLC cant see nothing either
in port scanner all ports closed
anything i forgot?
thanks

**Comment by cookins** [comment]
Update:
installed 0.85 version http seems working now and can see SSH server either.
but not RTSP! here log from sdcard
[log-197001010800.log](https://github.com/Filipowicz251/mijia-1080P-hacks/files/1853320/log-197001010800.log)
[log-Wifi-197001010800.log](https://github.com/Filipowicz251/mijia-1080P-hacks/files/1853321/log-Wifi-197001010800.log)
same RTSP log empty.

**Comment by willthrom** [comment]
update to 0.8.6.  it resolved an issue with RTSP
