### ISSUE TITLE
Not working with 0.8.6

### ISSUE THREAD

**Issue by passie** [Filipowicz251/mijia-1080P-hacks#43]
starting from the latest official release:

After downloading all the files from 0.8.6 the camera starts blinking the orange light.
Waiting a couple of minutes and the the led goed to off.
I'm unable to use the RTSP feature supported by this branch.
is there any complete how-to document starting from scratch, how-to use RTSP on this device ?

**Comment by naoisegolden** [comment]
Seems to be working fine in 0.8.7

**Comment by willthrom** [comment]
0.8.7 latest release fixed all the pending issues regarding Upgrading and RTSP

**Comment by passie** [comment]
With 0.8.7 I have the same problem.
Downloaded the latest rerelease with tf_recovery.img led start blinking orange.
After successful connecting the app it seems it's already at the latest version and i'm unable to use ssh or RTSP.
Any advice ?

**Comment by willthrom** [comment]
try again with tf_recovery.img (download it again) then check what version you are running. it should be .99
