### ISSUE TITLE
Not able to stream with Firmware 0159

### ISSUE THREAD

**Issue by zkornz** [Filipowicz251/mijia-1080P-hacks#47]
The hack was worked with blink led (Blue & Orange) Although I already set Enabled RTSP but I am still not watching RTSP streaming from VLC.  It's what I did for watching camera's IP is in MIWIFI application then I am using url like : rtsp://CAMERA_IP/live/ch00_0

I am able to SSH with new password
Log fie : 

Running Customm Script v1.8

Configuration:
  CLOUD_DISABLED=0
  CLOUD_STREAMING_DISABLED=0## Local Streaming. (0,1)
  RTSP_ENABLED=1## Local Streaming config -bBITRATE -fFRAMERATE -wWIDTH -hHEIGHT -mBITRATEMODE
  CONFIG_LINE=-b4098 -f20 -w1920 -h1080 -m1
  SSH_ROOT_PASS=159753korn
  DISABLED_OTA=0
  HTTP_ENABLED=0
  SAMBA_ENABLED=0
os-version
NAME=Buildroot
VERSION=2016.02-git-00808-g0de1356-dirty
ID=buildroot
VERSION_ID=2016.02-git
PRETTY_NAME="Buildroot 2016.02-git"
XIAOMI_VERSION=3.4.2_0159
XIAOMI_BUILDNO=458  
Forcing Mode 4
 Staring SSH Server
 Getting root access 
Changing password for root
New password: 
Retype password: 
Password for root changed by root

...Starting dropbear...
[208] Jan 01 07:00:09 Running in background

...Changing Language to English...
...Adding Protection to Change of Keys...

Script Ends. Ok
[1222] May 16 21:30:53 Child connection from 192.168.1.75:49414
[1222] May 16 21:31:40 Exit before auth (user 'root', 0 fails): Exited normally
[1234] May 16 21:32:02 Child connection from 192.168.1.75:49419
[1234] May 16 21:32:06 Login attempt for nonexistent user from 192.168.1.75:49419
[1234] May 16 21:32:18 Exit before auth: Exited normally
[1266] May 16 21:34:12 Child connection from 192.168.1.75:49423
[1266] May 16 21:34:22 Password auth succeeded for 'root' from 192.168.1.75:49423

Please help, I tried to do this more than a week

**Comment by willthrom** [comment]
this is weird:

> CLOUD_DISABLED=0
> CLOUD_STREAMING_DISABLED=0## Local Streaming. (0,1)

upload your midgard.ini file...

**Comment by zkornz** [comment]
@willthrom What should I edit in midgard.ini since I didn't do anything except enabling RTSP streaming. Thanks a lot.

**Comment by willthrom** [comment]
are you sure you are using the latest version "0.8.7 RTSP working back (Tested)"?

this release is working for a lot of people.

edit midgard.ini and remove anything after ##  it seems to have some conflict in your boot

**Comment by willthrom** [comment]
closed because inactivity and tested myself the latest Xiaomi version and it is working
