### ISSUE TITLE
Xiaomi Mijia 360 1080p - RTSP

### ISSUE THREAD

**Issue by niedzwiedziniec** [Filipowicz251/mijia-1080P-hacks#67]
Will the tutorial and files from the topic (https://github.com/Filipowicz251/mijia-1080P-hacks/issues/5) 
 or other work with the Mijia 360 1080p camera - if not, do you plan to work on running rtsp in this camera

i mean this camera: 
![image](https://user-images.githubusercontent.com/6079142/72723490-1194b600-3b81-11ea-987c-40b6790a49b8.png)

**Comment by willthrom** [comment]
Each Xioami has a different hardware, and even if the hardware could be the same, the files inside are not.
Unless some will continue might work, the project is dead.
