### ISSUE TITLE
[TASK] RTSP 555Live version

### ISSUE THREAD

**Issue by willthrom** [Filipowicz251/mijia-1080P-hacks#8]

**Comment by andreq** [comment]
Did anyone figure out a way to share a VirtualBox or any kind of VM of the dev environment? I'm quite bad at the whole setup of those sadly.

**Comment by willthrom** [comment]
Installing VM is the easy part.

Have you give it a try? Installing virtual box, the load a Linux Image, like "lubuntu".. and then just follow the instructions in the SDK...

**Comment by andreq** [comment]
I admit, I didn't try anything yet for this camera, but last time I worked on an embedded device I lost many nights and never got a good working setup. Ended up compiling on the device itself, which took ages. I'll see if I find some time to play with it this week-end. 
Btw, good freaking job figuring all the detail to get this thing up and running!

**Comment by willthrom** [comment]
The toolchain is very easy to install, the SDK has all you need.

**Comment by papplampe1** [comment]
Wow. SSH and RTSP working with your script with the old firmware on my camera. good job. did not realize you were that avanced in the project until i tried it.

**Comment by willthrom** [comment]
@papplampe1 you can upgrade to the latest firmware. it should work. If not, let me know. (you can try to remove the ft folder from the SDCARD if after upgrading to 139 it doesn´t work.

**Comment by jonas-olofsson** [comment]
How do I access the current rtsp stream from the camera after applying the hack?
-- Edit - 
Yes it is, in bold and everything! Sorry but totally missed it... 

Added a PR to add it to readme as well

**Comment by willthrom** [comment]
Isn't it in the instructions?

**Comment by jonas-olofsson** [comment]
Yes it is, in bold and everything! Sorry but totally missed it...

**Comment by kollaesch** [comment]
@willthrom 
kudos! :octocat: Impressive work! 👍 🥇 🍰  

__To follow-up on the VM:__ Did you learn anything new about setting up the SDK ?
My docker is running, but still couldn't successfully build anything.
Additional starting tipps? 😋

**Comment by willthrom** [comment]
I attached in one of those post a full makefile with a demo program... you only need to run make on it....
The SDK only needs to be decompress is a folder..... all very well described in the SDK Documentation.

**Comment by andreq** [comment]
I got my old Ubuntu VM back up and running. Compiled your test app successfully!
Right now I'm try to cross-compile gstreamer, but it might be overkill for now and I'm a bit lost. 

I was able to configure the makefile "properly" with
`./configure --host=arm-linux-gnueabi --prefix=/usr/src/arm-linux-3.3/toolchain_gnueabi-4.4.0_ARMv5TE/usr/local/ --enable-gtk-doc --disable-examples --includedir=//usr/src/arm-linux-3.3/toolchain_gnueabi-4.4.0_ARMv5TE/usr/include/ --libdir=/usr/src/arm-linux-3.3/toolchain_gnueabi-4.4.0_ARMv5TE/usr/local/lib/ --exec-prefix=/usr/src/arm-linux-3.3/toolchain_gnueabi-4.4.0_ARMv5TE/usr/local/
`
(and install a bunch of dependencies).

I can make all with success, but I'm stuck there trying to figure out how to package the ouput to install on the camera. This is where my knowledge stop :(

Edit : I went ahead and tried  make dist-zip.
It created that zip file if anyone wanna try it. I'm off to bed and won't have time to play with that for a little while.
[gstreamer-1.13.0.1.zip](https://github.com/Filipowicz251/mijia-1080P-hacks/files/1378000/gstreamer-1.13.0.1.zip)
Edit 2 : This just packaged my freaking build folder without any compiled file -_-... I'll fiddle more and update if I get anything.

**Comment by willthrom** [comment]
--prefix is the destination folder. you don't want to use the toolchain.
The --host is normally "arm-linux" or the  prefix of the compiler.
you don't need to add the includes of the toolchain. neither the libdir or --exec-prefix. normally autocalculated

Check if ./configure has an option for "CROSSCOMPILER"

Normally the output will go to the "prefix" folder when you run make install

--prefix=/home/XXX/rootfs for example

**Comment by andreq** [comment]
So, I haven't got any deeper, even tho it compiled. I think I'm aiming at the solution the wrong way. 

Is there plan to share the modified RTSP code from the SDK so we can work from that? I can compile the original code easily and run it, I just didn't change anything yet.

**Comment by willthrom** [comment]
@andreq  I upload the code I developed for the RTSP server to https://github.com/willthrom/rtspServer_gm

feel free to take a look and work on it.

**Comment by whuang1965** [comment]
Does it support sound?

**Comment by willthrom** [comment]
No sound for now...

**Comment by TigerChi** [comment]
Thanks for RTSP Server ! 
It's really great to streaming in local network for multi-camera.
If can support sound, I think it will perfect !

**Comment by ant-1** [comment]
Hello guys !

It seems that Andreq succeeded to cross compile Gstreamer. Has anyone tried to use this RTSP server ?
Thanks !

**Comment by ohohei** [comment]
hello guys！
I‘m trying to use live555 on linux,but I meet a promblem,
--------------------------------------------------------------------------------------------------------------------
BasicTaskScheduler.cpp: In member function ‘virtual void BasicTaskScheduler::SingleStep(unsigned int)’:
BasicTaskScheduler.cpp:191:40: error: ‘struct std::atomic_flag’ has no member named ‘test’
  191 |       if (fTriggersAwaitingHandling[i].test()) {
      |                                        ^~~~
make[1]: *** [Makefile:41: BasicTaskScheduler.o] Error 1
make[1]: Leaving directory '/home/linaro/live555/live/BasicUsageEnvironment'
make: *** [Makefile:50: install] Error 2
----------------------------------------------------------------------------------------------------------------------
so,I'm really want a compatible vison,Thinks

**Comment by willthrom** [comment]
This is normally a problem with the version of the libraries.
std::atomic is from the standard library, so depending on the version of the compiler, the library AND the live555 library you might get a successfull compilation or not.

Check the dependencies for the live555 library version you are using.
